version: '3.8'

services:
  payment-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - FRAUD_THRESHOLD=0.5
      - LARGE_AMOUNT_THRESHOLD=5000
      - SUSPICIOUS_DOMAINS=.ru,.test.com,.example.com
      - LOG_LEVEL=info
      - ALLOWED_ORIGINS=http://localhost:3000,https://yourdomain.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/monitor/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge
